"""Validate that fixture references in scenarios are well-formed and
that no fixture files are orphaned."""
from __future__ import annotations

from pathlib import Path


def _collect_fixture_refs(scenarios: list[dict]) -> set[str]:
    refs: set[str] = set()
    for s in scenarios:
        for ref in s.get("workspace_files", {}).values():
            if isinstance(ref, str) and ref.startswith("@fixtures/"):
                refs.add(ref[len("@fixtures/"):])
    return refs


def _collect_fixture_files(fixtures_dir: Path) -> set[str]:
    """Collect canonical fixture files.

    The ``variants/`` subtree is a parallel cast generated by
    ``tools/workspace_variants.py``; it is referenced only from
    ``scenarios.<variant>.json`` / ``open-ended.<variant>.json`` and is
    intentionally *not* required to be referenced from the canonical
    scenarios.json. Skip it here.
    """
    files: set[str] = set()
    for p in fixtures_dir.rglob("*"):
        if p.is_file():
            rel = p.relative_to(fixtures_dir).as_posix()
            if rel.startswith("variants/"):
                continue
            files.add(rel)
    return files


def test_mcq_fixture_refs_exist(scenarios, fixtures_dir: Path):
    for ref in _collect_fixture_refs(scenarios):
        path = fixtures_dir / ref
        assert path.exists(), f"Missing fixture referenced by MCQ: {path}"
        assert path.is_file(), f"Fixture ref is not a file: {path}"


def test_open_ended_fixture_refs_exist(open_ended, fixtures_dir: Path):
    for ref in _collect_fixture_refs(open_ended):
        path = fixtures_dir / ref
        assert path.exists(), f"Missing fixture referenced by open-ended: {path}"
        assert path.is_file(), f"Fixture ref is not a file: {path}"


def test_no_orphan_fixtures(scenarios, open_ended, fixtures_dir: Path):
    """Every file under fixtures/ should be referenced by at least one
    scenario (MCQ or open-ended)."""
    referenced = _collect_fixture_refs(scenarios) | _collect_fixture_refs(open_ended)
    on_disk = _collect_fixture_files(fixtures_dir)
    orphans = sorted(on_disk - referenced)
    assert not orphans, (
        f"Fixture files not referenced by any scenario:\n  - "
        + "\n  - ".join(orphans)
    )


def test_all_refs_have_canonical_slash_form(scenarios, open_ended):
    """Fixture refs should use forward slashes for cross-platform compat."""
    for dataset in (scenarios, open_ended):
        for s in dataset:
            for filename, ref in s.get("workspace_files", {}).items():
                if isinstance(ref, str) and ref.startswith("@fixtures/"):
                    assert "\\" not in ref, (
                        f"Scenario #{s.get('id')} fixture ref uses "
                        f"backslash: {ref!r}"
                    )


def test_fixtures_directory_exists(fixtures_dir: Path):
    assert fixtures_dir.exists() and fixtures_dir.is_dir()
