#!/usr/bin/env python3
"""
HuggingFace ``datasets`` loading script for PM-Bench.

This script is intended to ship with the dataset repo on the Hub as
``pm_bench.py`` (or be uploaded under that name). It supports three configs:

    load_dataset("pm_bench", "mcq")         -> 68 MCQ/keyword scenarios
    load_dataset("pm_bench", "open-ended")  -> 20 open-ended judgment scenarios
    load_dataset("pm_bench", "superhuman")  -> 20 Superhuman PM Judgment MCQ
                                               (category-filtered from mcq)

All three configs read from the JSONL files generated by
``prepare_hf_dataset.py``. The script expects ``mcq.jsonl`` and
``open-ended.jsonl`` to sit next to it in the dataset repo.
"""

from __future__ import annotations

import json
from pathlib import Path

import datasets

_CITATION = """\
@software{pm_bench_2026,
  author  = {Kern, Alan},
  title   = {{PM-Bench}: A Benchmark for AI PM Judgment in a Noisy Engineering Workspace},
  year    = {2026},
  url     = {https://github.com/KernAlan/pm-bench},
  license = {MIT}
}
"""

_DESCRIPTION = """\
PM-Bench is a benchmark for AI PM judgment in a noisy engineering workspace.
It contains 68 MCQ/keyword scenarios across 10 categories plus 20 open-ended
scenarios that strip the multiple-choice scaffolding to test unprompted
judgment. Scenarios are grounded in realistic simulated team workspaces with
real PM failure modes: hidden dependencies, misleading metrics, missing
commitments, single-point-of-failure risk, and knowing when to stay quiet.
"""

_HOMEPAGE = "https://github.com/KernAlan/pm-bench"
_LICENSE = "MIT"

_MCQ_FILE = "mcq.jsonl"
_OPEN_FILE = "open-ended.jsonl"

_SUPERHUMAN_CATEGORY = "Superhuman PM Judgment"


class PmBenchConfig(datasets.BuilderConfig):
    """Config for PM-Bench subsets."""

    def __init__(self, *, source_file: str, category_filter: str | None = None,
                 **kwargs):
        super().__init__(**kwargs)
        self.source_file = source_file
        self.category_filter = category_filter


class PmBench(datasets.GeneratorBasedBuilder):
    """PM-Bench: AI PM judgment benchmark."""

    VERSION = datasets.Version("1.0.0")

    BUILDER_CONFIGS = [
        PmBenchConfig(
            name="mcq",
            version=VERSION,
            description="68 MCQ/keyword scenarios across 10 categories.",
            source_file=_MCQ_FILE,
        ),
        PmBenchConfig(
            name="open-ended",
            version=VERSION,
            description="20 open-ended scenarios with rubric + LLM-judge scoring.",
            source_file=_OPEN_FILE,
        ),
        PmBenchConfig(
            name="superhuman",
            version=VERSION,
            description="20 Superhuman PM Judgment MCQ (category-filtered).",
            source_file=_MCQ_FILE,
            category_filter=_SUPERHUMAN_CATEGORY,
        ),
    ]

    DEFAULT_CONFIG_NAME = "mcq"

    def _info(self) -> datasets.DatasetInfo:
        if self.config.name == "open-ended":
            features = datasets.Features(
                {
                    "id": datasets.Value("int32"),
                    "source_mcq_id": datasets.Value("int32"),
                    "name": datasets.Value("string"),
                    "category": datasets.Value("string"),
                    "context": datasets.Value("string"),
                    "trigger": datasets.Value("string"),
                    "must_mention": datasets.Sequence(datasets.Value("string")),
                    "should_mention": datasets.Sequence(datasets.Value("string")),
                    "red_flags": datasets.Sequence(datasets.Value("string")),
                    "judge_prompt": datasets.Value("string"),
                }
            )
        else:
            features = datasets.Features(
                {
                    "id": datasets.Value("int32"),
                    "name": datasets.Value("string"),
                    "category": datasets.Value("string"),
                    "scoring": datasets.Value("string"),
                    "context": datasets.Value("string"),
                    "trigger": datasets.Value("string"),
                    "correct_answer": datasets.Value("string"),
                    "expected_tools": datasets.Sequence(datasets.Value("string")),
                }
            )
        return datasets.DatasetInfo(
            description=_DESCRIPTION,
            features=features,
            homepage=_HOMEPAGE,
            license=_LICENSE,
            citation=_CITATION,
        )

    def _split_generators(self, dl_manager):
        # Files live alongside this script in the dataset repo.
        local_path = Path(dl_manager.download(self.config.source_file))
        return [
            datasets.SplitGenerator(
                name=datasets.Split.TRAIN,
                gen_kwargs={"filepath": str(local_path)},
            ),
        ]

    def _generate_examples(self, filepath: str):
        cat_filter = self.config.category_filter
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                if cat_filter and row.get("category") != cat_filter:
                    continue
                # Key yields must be unique and stable.
                yield row["id"], row
