#!/usr/bin/env python3
"""
Update LEADERBOARD.md from results/*.json files.

Aggregates by (model, mode, subset). For each (model, mode, subset) tuple,
computes mean accuracy, std, and 95% CI across all matching iteration files.

Usage:
    python tools/update_leaderboard.py
"""

import glob
import json
import math
import os
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = ROOT / "results"
LEADERBOARD = ROOT / "LEADERBOARD.md"


def load_results():
    out = []
    for path in sorted(glob.glob(str(RESULTS_DIR / "*.json"))):
        d = json.load(open(path))
        if d.get("provider") == "mock":
            continue
        d["_path"] = os.path.basename(path)
        out.append(d)
    return out


def aggregate(runs):
    """Return {(model, mode, subset): [accuracies]} where subset is sh20|full|open20."""
    groups = defaultdict(list)
    for r in runs:
        mode = r.get("mode", "mcq")
        model = r.get("model", "?")
        provider = r.get("provider", "?")
        total = r.get("total", 0)
        correct = r.get("correct", 0)
        if total == 0:
            continue
        # Determine subset
        if mode == "open-ended":
            subset = "open20"
        elif mode == "agentic":
            subset = f"agentic{total}"
        elif total == 20:
            subset = "sh20"
        else:
            subset = f"full{total}"
        key = (provider, model, mode, subset)
        groups[key].append(correct / total)
    return groups


def ci95(values):
    n = len(values)
    if n == 0:
        return 0.0, 0.0, 0.0
    mean = sum(values) / n
    if n == 1:
        return mean, 0.0, 0.0
    var = sum((v - mean) ** 2 for v in values) / (n - 1)
    std = math.sqrt(var)
    ci = 1.96 * std / math.sqrt(n)
    return mean, std, ci


def render_table(groups, mode_filter, subset_filter, title, columns):
    rows = []
    for (provider, model, mode, subset), values in groups.items():
        if mode != mode_filter or subset != subset_filter:
            continue
        mean, std, ci = ci95(values)
        rows.append((mean, model, provider, len(values), mean * 100, ci * 100))
    rows.sort(key=lambda x: -x[0])

    out = [f"## {title}\n"]
    out.append("| Rank | Model | Provider | Score | 95% CI | Iterations |")
    out.append("|------|-------|----------|-------|--------|------------|")
    if not rows:
        out.append("| — | (no submissions yet) | — | — | — | — |")
    else:
        for rank, (_, model, provider, n, pct, ci_pct) in enumerate(rows, 1):
            ci_str = f"±{ci_pct:.2f}%" if n > 1 else "n=1"
            out.append(f"| {rank} | `{model}` | {provider} | {pct:.2f}% | {ci_str} | {n} |")
    return "\n".join(out) + "\n"


def render_leaderboard(groups, scenario_count_full):
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = []
    out.append("# PM-Bench Leaderboard\n")
    out.append(f"Last updated: {today} (auto-generated by `tools/update_leaderboard.py`)\n")
    out.append("PM-Bench v1.0.0. Scores cited as: mean across N iterations, "
               "with 95% CI = 1.96 × (std / sqrt(N)). Single-iteration runs show n=1.\n")

    out.append(render_table(groups, "mcq", "sh20",
               "MCQ — Superhuman 20 (`--superhuman-only`)",
               None))

    out.append(render_table(groups, "mcq", f"full{scenario_count_full}",
               f"MCQ — Full {scenario_count_full} (all auto-scored)",
               None))

    out.append(render_table(groups, "open-ended", "open20",
               "Open-Ended — 20 scenarios (rubric + LLM-judge)",
               None))

    out.append(render_table(groups, "agentic", "agentic20",
               "Agentic — Superhuman 20 (model uses list_files / read_file / grep)",
               None))
    out.append(render_table(groups, "agentic", f"agentic{scenario_count_full}",
               f"Agentic — Full {scenario_count_full} (tool-use evaluation)",
               None))

    out.append("## Human Baselines\n\n"
               "Human-PM baselines help contextualize model scores. To "
               "contribute, see [HUMAN_BASELINE.md](HUMAN_BASELINE.md).\n\n"
               "| Participant Background | Mode | Score | N Scenarios | Time per Scenario |\n"
               "|------------------------|------|-------|-------------|-------------------|\n"
               "| (no baselines yet)     | —    | —     | —           | —                 |\n")

    out.append("## How scores are computed\n\n"
               "Each reported score is the mean of N iterations against the deterministic "
               "scoring rubric in `run.py`. 95% CI uses the normal approximation "
               "1.96 × std / sqrt(N). Submissions with N=1 are shown but not directly "
               "comparable in confidence — three or more iterations are recommended.\n\n"
               "Open-ended mode uses an LLM judge. The reported judge model is whichever "
               "the submitter passed via `--judge-model`. Submissions where subject and judge "
               "are the same model family should be flagged as potentially self-biased.\n")

    out.append("## How to submit\n\n"
               "1. Run `python run.py [--mode open-ended] [--superhuman-only]` "
               "at least 3 iterations.\n"
               "2. Verify your `results/*.json` files exist.\n"
               "3. Open a PR adding your row, attach raw results to "
               "`submissions/<provider>-<model>/<date>/`.\n"
               "4. Or open an Issue with results — maintainers can re-run for verification.\n")

    return "\n".join(out)


def main():
    runs = load_results()
    if not runs:
        print("No results found in", RESULTS_DIR)
        return
    groups = aggregate(runs)

    # Detect the full-scenario size from any non-superhuman MCQ run.
    full_size = 48
    for k in groups:
        _, _, mode, subset = k
        if mode == "mcq" and subset.startswith("full"):
            full_size = int(subset[4:])
            break

    md = render_leaderboard(groups, full_size)
    LEADERBOARD.write_text(md, encoding="utf-8")
    print(f"Wrote {LEADERBOARD}  ({len(md)} chars, {len(runs)} runs aggregated)")


if __name__ == "__main__":
    main()
